### PR TITLE
Allow to browserify plugins folders who don't have an "index.ts" file.

### PR DESCRIPTION
**Pull request by florentpoujol**

### CODE REVIEW

**Comment by bilou84** [comment]
This is good call, but that will break stuff.
On the first build, the Javascript doesn't exist since the TypeScript compilation hasn't been done yet. (for plugins using TypeScript of course)

The best solution would probably to check either the TypeScript file or the Javascript file ?

**Comment by florentpoujol** [comment]
Yes I was wondering what could it break.
But if there is no way to make sure the browserification only runs after the Typescript task has completed, checking for the .ts OR .js file doesn't solve that issue (since there is no guarantee that the .js file already exists when the browserification starts)...

At least it should allow to browserify folders which only have a .js files.
I will update the pull request tomorrow.

**Comment by bilou84** [comment]
I was thinking for plugins with only Javascript indeed, since it is working fine with TypeScript.
Did you have something else in mind ?

**Comment by florentpoujol** [comment]
Actually it doesn't matter which tasks comes first since this code is executed before any tasks is started.
So now it works whatever the content of the folders is, Typescript or Javascript.

Also why is the "data-browserify" tasks always created, event when the folder doesn't exists ?

**Comment by bilou84** [comment]
The data-browserify by default is a mistake. Fixing it right away

**Comment by elisee** [comment]
:+1:

**Pull request merged**
