### PR TITLE
Create an url which always serves the last build

### PR DESCRIPTION
**Pull request by Pangoraw**

### CODE REVIEW

**Comment by bilou84** [comment]
Hey thanks!
We were thinking of using the nextBuildId (minus 1) on the ProjectServer instead of read the folder everytime. Can you try this out ?

**Comment by Pangoraw** [comment]
I will try this because readFolder expect the build folder to be "clean".

**Comment by elisee** [comment]
Yeah I don't think `fs.readdirSync` doesn't offer any guarantee of result order so you can't just take the last returned folder and expect it to always be the most recently created or anything like that. Definitely best to use `nextBuildId - 1`

**Comment by Pangoraw** [comment]
Something like ```if (req.params.buildId === "latest") nextBuildId = projectServer.nextBuidId - 1; ``` should work ?

**Comment by bilou84** [comment]
Probably just `buildId = projectServer.nextBuildId - 1;` ?

**Comment by Pangoraw** [comment]
Yes I meant ````buildId```. I got it updated.

**Comment by elisee** [comment]
`path.join` only accepts strings as arguments so I added a call to `.toString()`. Amended and squashed the two commits into a single ce751d36d632afefa620a532b45003b85e5c4421.

Thanks!

**Pull request closed without merging**
