### PR TITLE
Replace `<Type>x` with `x as Type` (fixes #21)

### LINKED ISSUE #21: Replace all usage of `<Type>expression` with `expression as Type`
The `as` operator is more readable and it's the recommended operator going forward because of clashes with JSX syntax.

Like #14, this is an easy but somewhat menial task that might take a while so feel free to do a couple files at a time if you want to get started contributing!

See Microsoft/TypeScript#3564 and https://facebook.github.io/react/docs/jsx-in-depth.html

### PR DESCRIPTION
**Pull request by Xstoudi**
I wrote a script who replace every "<type>expression" by "(expression as type)" (#21). It seems to work.

### CODE REVIEW

**Comment by elisee** [comment]
Looks good. Can you amend the commit message & force push your branch? As listed in [the documentation](http://docs.superpowers-html5.com/en/development/how-to-contribute):

> * Use imperative in your commits message, for instance `Add flux capacitor` not `Added a flux capacitor`
> * If you're fixing a bug with an existing issue number of GitHub, mention it in the commit message: `Increase gigawatt output, closes #6`

Something like `Use as keyword for type assertions everywhere, fixes #21` would be great.

Thanks!

**Comment by elisee** [comment]
Did you try building Superpowers from source with your changes? There are quite a few errors because of misplaced parentheses ^_^.

For instance, in SupCore/Data/Base.index.ts:

 * `let items = (rule as string[]).items;` Should have been: `let items = rule.items as string[];`
 * `(rule as Rule).items` should have been `rule.items as Rule`

In SupCore/Data/Entries.ts, `(this as EntryNode).byId[id]` should have been `this.byId[id] as EntryNode`, etc.

Can you try updating the script to fix it, rebuilding and force pushing a corrected commit?

**Comment by Xstoudi** [comment]
(Sorry for the delay)
I have not managed to create a valid regexp to do this automatically, but the script can find the lines to change. 
https://gist.github.com/Xstoudi/dd75d95e0a8a6f1d1c64

**Comment by Xstoudi** [comment]
You can close the other pull request, I failed to rebase...

**Comment by elisee** [comment]
By the other pull request, you mean this one, right?

**Pull request closed without merging**
